language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t thibaultfrossard/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true thibaultfrossard/docker-react npm run test